import { useState } from 'react'
import { Bell, Check, Heart, MapPin } from 'lucide-react'
import Header from '../components/layout/Header'

export default function AssistPage({ back, notify }) {
    const [step, setStep] = useState('form')
    const [fuel, setFuel] = useState('PB 95')
    return <><Header title="Pomoc przy tankowaniu" back onBack={back} /><main className="page assist-page"><section className="assist-hero"><span><Heart fill="currentColor" /></span><p className="eyebrow">Jesteśmy dla Ciebie</p><h1>Poproś obsługę o pomoc</h1><p>Pracownik podejdzie do Twojego samochodu i pomoże Ci bezpiecznie zatankować.</p></section>{step === 'form' ? <section className="card form-card"><label>Wybrana stacja<div className="fake-input"><MapPin /><span><strong>Orzeł Modlińska</strong><small>ul. Modlińska 8</small></span></div></label><label>Szacowany czas przyjazdu<select><option>Jestem już na stacji</option><option>Za około 5 minut</option><option>Za około 10 minut</option></select></label><label>Rodzaj paliwa<div className="choice-row">{['PB 95', 'PB 98', 'ON', 'LPG'].map(x => <button className={fuel === x ? 'active' : ''} onClick={() => setFuel(x)} key={x}>{x}</button>)}</div></label><button className="wide-button" onClick={() => { setStep('waiting'); setTimeout(() => setStep('accepted'), 1600) }}>Wyślij prośbę o pomoc</button></section> : <section className="card waiting-card"><div className={step === 'accepted' ? 'accepted status-animation' : 'status-animation'}>{step === 'accepted' ? <Check /> : <Bell />}</div><p className="eyebrow">{step === 'accepted' ? 'Zgłoszenie przyjęte' : 'Powiadamiamy obsługę'}</p><h2>{step === 'accepted' ? 'Marek jest w drodze' : 'Prosimy o chwilę'}</h2><p>{step === 'accepted' ? 'Pracownik podejdzie do Twojego auta za około 2 minuty.' : 'Szukamy dostępnego pracownika na stacji.'}</p>{step === 'accepted' && <><div className="employee"><div>MK</div><span><strong>Marek Kowalski</strong><small>Pracownik stacji</small></span><span>~2 min</span></div><button className="wide-button secondary" onClick={() => { notify('Zgłoszenie pomocy anulowane'); back() }}>Anuluj zgłoszenie</button></>}</section>}</main></>
}
